azure_region         = "centralus"
azure_environment    = "dev"
resource_name_suffix = "748"
apim_publisher_name  = "Cool Revive"
apim_publisher_email = "chadgreen@chadgreen.com"
apim_sku_name        = "Developer_1"